"""Shared constants and helper functions for node implementations.

This module intentionally re-exports helper utilities from ``nodes_impl`` to keep
behavior identical during the refactor while providing clearer module boundaries.
"""

from research_agent.nodes_impl import (
    AGENT_REQUIREMENTS,
    TOP_REQUIREMENTS_CONTRACT,
    CRITIC_HARD_GATES,
    CRITIC_SOFT_GATES,
    _build_paper_context,
    _to_json,
    _clip_text,
    _dedupe_keep_order,
    _normalize_text_key,
    _dedupe_by_normalized_key,
    _limit_items,
    _dedupe_limit_items,
    _split_critic_failed_gates,
    _estimate_information_gain,
    _extract_goal_ids_from_claims,
    _split_rag_chunks,
    _is_education_multiagent_relevant,
    _compute_rag_hit_stats,
    _split_actions_for_roles,
    _contains_negated_self_report,
    _has_explicit_positive_self_report,
    _detect_explicit_self_report,
    _truncate_middle,
    _compact_writer_claims,
    _compact_evidence_cards,
    _extract_between,
    _critic_hard_fail_checks,
    _method_depth_audit,
    _experiment_depth_audit,
    _result_balance_audit,
    _method_detail_completeness_audit,
    _motivation_overweight_audit,
    _goal_ids_from_tool,
    _rewrite_rag_query,
)

__all__ = [
    "AGENT_REQUIREMENTS",
    "TOP_REQUIREMENTS_CONTRACT",
    "CRITIC_HARD_GATES",
    "CRITIC_SOFT_GATES",
    "_build_paper_context",
    "_to_json",
    "_clip_text",
    "_dedupe_keep_order",
    "_normalize_text_key",
    "_dedupe_by_normalized_key",
    "_limit_items",
    "_dedupe_limit_items",
    "_split_critic_failed_gates",
    "_estimate_information_gain",
    "_extract_goal_ids_from_claims",
    "_split_rag_chunks",
    "_is_education_multiagent_relevant",
    "_compute_rag_hit_stats",
    "_split_actions_for_roles",
    "_contains_negated_self_report",
    "_has_explicit_positive_self_report",
    "_detect_explicit_self_report",
    "_truncate_middle",
    "_compact_writer_claims",
    "_compact_evidence_cards",
    "_extract_between",
    "_critic_hard_fail_checks",
    "_method_depth_audit",
    "_experiment_depth_audit",
    "_result_balance_audit",
    "_method_detail_completeness_audit",
    "_motivation_overweight_audit",
    "_goal_ids_from_tool",
    "_rewrite_rag_query",
]

